FROM node:stretch

# to avoid acces denied error when trying to use docker volumes

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./

RUN npm install

COPY --chown=node:node . .

CMD ["npm", "run", "start"]